// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AnnotationsForm: typeof import("./components/form/AnnotationsForm.vue")["default"];
    CategoryDropdownSelector: typeof import("./components/dropdown-selector/CategoryDropdownSelector.vue")["default"];
    DefaultEditor: typeof import("./components/editor/DefaultEditor.vue")["default"];
    EditorProviderSelector: typeof import("./components/dropdown-selector/EditorProviderSelector.vue")["default"];
    FilterCleanButton: typeof import("./components/filter/FilterCleanButton.vue")["default"];
    FilterTag: typeof import("./components/filter/FilterTag.vue")["default"];
    GlobalSearchModal: typeof import("./components/global-search/GlobalSearchModal.vue")["default"];
    IconAddCircle: typeof import("@halo-dev/components")["IconAddCircle"];
    IconArrowDown: typeof import("@halo-dev/components")["IconArrowDown"];
    IconArrowDownCircleLine: typeof import("@halo-dev/components")["IconArrowDownCircleLine"];
    IconArrowLeft: typeof import("@halo-dev/components")["IconArrowLeft"];
    IconArrowRight: typeof import("@halo-dev/components")["IconArrowRight"];
    IconArrowUpCircleLine: typeof import("@halo-dev/components")["IconArrowUpCircleLine"];
    IconBookRead: typeof import("@halo-dev/components")["IconBookRead"];
    IconCheckboxFill: typeof import("@halo-dev/components")["IconCheckboxFill"];
    IconCloseCircle: typeof import("@halo-dev/components")["IconCloseCircle"];
    IconDashboard: typeof import("@halo-dev/components")["IconDashboard"];
    IconDatabase2Line: typeof import("@halo-dev/components")["IconDatabase2Line"];
    IconDeleteBin: typeof import("@halo-dev/components")["IconDeleteBin"];
    IconExchange: typeof import("@halo-dev/components")["IconExchange"];
    IconExternalLinkLine: typeof import("@halo-dev/components")["IconExternalLinkLine"];
    IconEye: typeof import("@halo-dev/components")["IconEye"];
    IconEyeOff: typeof import("@halo-dev/components")["IconEyeOff"];
    IconFolder: typeof import("@halo-dev/components")["IconFolder"];
    IconGitHub: typeof import("@halo-dev/components")["IconGitHub"];
    IconLink: typeof import("@halo-dev/components")["IconLink"];
    IconList: typeof import("@halo-dev/components")["IconList"];
    IconListSettings: typeof import("@halo-dev/components")["IconListSettings"];
    IconMessage: typeof import("@halo-dev/components")["IconMessage"];
    IconMore: typeof import("@halo-dev/components")["IconMore"];
    IconPages: typeof import("@halo-dev/components")["IconPages"];
    IconPalette: typeof import("@halo-dev/components")["IconPalette"];
    IconPlug: typeof import("@halo-dev/components")["IconPlug"];
    IconRefreshLine: typeof import("@halo-dev/components")["IconRefreshLine"];
    IconReplyLine: typeof import("@halo-dev/components")["IconReplyLine"];
    IconSave: typeof import("@halo-dev/components")["IconSave"];
    IconSettings: typeof import("@halo-dev/components")["IconSettings"];
    IconShieldUser: typeof import("@halo-dev/components")["IconShieldUser"];
    IconStopCircle: typeof import("@halo-dev/components")["IconStopCircle"];
    IconTeam: typeof import("@halo-dev/components")["IconTeam"];
    IconUpload: typeof import("@halo-dev/components")["IconUpload"];
    IconUserFollow: typeof import("@halo-dev/components")["IconUserFollow"];
    IconUserSettings: typeof import("@halo-dev/components")["IconUserSettings"];
    LazyImage: typeof import("./components/image/LazyImage.vue")["default"];
    LoginForm: typeof import("./components/login/LoginForm.vue")["default"];
    LoginModal: typeof import("./components/login/LoginModal.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SubmitButton: typeof import("./components/button/SubmitButton.vue")["default"];
    TagDropdownSelector: typeof import("./components/dropdown-selector/TagDropdownSelector.vue")["default"];
    UppyUpload: typeof import("./components/upload/UppyUpload.vue")["default"];
    UrlPreviewModal: typeof import("./components/preview/UrlPreviewModal.vue")["default"];
    UserDropdownSelector: typeof import("./components/dropdown-selector/UserDropdownSelector.vue")["default"];
    VAlert: typeof import("@halo-dev/components")["VAlert"];
    VAvatar: typeof import("@halo-dev/components")["VAvatar"];
    VButton: typeof import("@halo-dev/components")["VButton"];
    VCard: typeof import("@halo-dev/components")["VCard"];
    VCodemirror: typeof import("@halo-dev/components")["VCodemirror"];
    VEmpty: typeof import("@halo-dev/components")["VEmpty"];
    VEntity: typeof import("@halo-dev/components")["VEntity"];
    VEntityField: typeof import("@halo-dev/components")["VEntityField"];
    VLoading: typeof import("@halo-dev/components")["VLoading"];
    VModal: typeof import("@halo-dev/components")["VModal"];
    VPageHeader: typeof import("@halo-dev/components")["VPageHeader"];
    VPagination: typeof import("@halo-dev/components")["VPagination"];
    VSpace: typeof import("@halo-dev/components")["VSpace"];
    VStatusDot: typeof import("@halo-dev/components")["VStatusDot"];
    VSwitch: typeof import("@halo-dev/components")["VSwitch"];
    VTabbar: typeof import("@halo-dev/components")["VTabbar"];
    VTabItem: typeof import("@halo-dev/components")["VTabItem"];
    VTabs: typeof import("@halo-dev/components")["VTabs"];
    VTag: typeof import("@halo-dev/components")["VTag"];
  }
}
